name: tutorial
version: '${project.version}'
main: tutorial.tutorial.Tutorial
api-version: '1.18'
commands:
  fly:
    description: Toggles Flying for sender
    usage: /fly
    aliases: []
    permissions: fly
  menu:
    description: Toggles Menu
    usage: /menu
    aliases: m
  rtp:
    description: Random Teleport
    usage: /rtp
    aliases: []
